/**
 * Product data for commerce (build-time static).
 * Replace with CMS or API later if needed.
 */

// Product categories
export const PRODUCT_CATEGORIES = {
  FMCG: 'Food & Beverages',
  AUTOPARTS: 'Autoparts',
  ELECTRONICS: 'Electronics',
  FABRICS: 'Fabrics',
  AGRIC_INPUTS: 'Agricultural Inputs',
} as const;

export type ProductCategory = typeof PRODUCT_CATEGORIES[keyof typeof PRODUCT_CATEGORIES];

export type Product = {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;          // Use 0 for "Price on Request"
  currency: string;       // "GHS"
  image: string;
  category: string;       // Required - one of PRODUCT_CATEGORIES
  sku?: string;           // Optional SKU for inventory tracking
  inStock?: boolean;      // Optional stock status (default true)
  tags?: string[];        // Optional tags for filtering
  featured?: boolean;     // Featured product flag
};

export const PRODUCTS: Product[] = [
  // ─── Oil Filters ───────────────────────────────────────────────────────────
  {
    id: '1',
    slug: 'gm-vehicles-oil-filter-pf63e',
    name: 'GM Vehicles Oil Filter (PF63E)',
    description: 'High-efficiency oil filter for GM vehicles. Part No. PF63E. OEM-grade filtration for engine longevity.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'PF63E',
    inStock: true,
  },
  {
    id: '2',
    slug: 'ford-vehicles-oil-filter-fl500s',
    name: 'Ford Vehicles Oil Filter (FL500S)',
    description: 'Oil filter for Ford vehicles. Part No. FL500S. Reliable engine protection for Ford models.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'FL500S',
    inStock: true,
  },
  {
    id: '3',
    slug: 'gm-vehicles-oil-filter-pf48',
    name: 'GM Vehicles Oil Filter (PF48)',
    description: 'Oil filter for GM vehicles. Part No. PF48. Quality filtration designed to OEM specifications.',
    price: 52,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'PF48',
    inStock: true,
  },
  {
    id: '4',
    slug: 'ford-vehicles-oil-filter-fl910s',
    name: 'Ford Vehicles Oil Filter (FL910S)',
    description: 'Oil filter for Ford vehicles. Part No. FL910S. Ensures clean oil flow for optimal engine performance.',
    price: 49,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'FL910S',
    inStock: true,
  },
  {
    id: '5',
    slug: 'gm-vehicles-oil-filter-pf64',
    name: 'GM Vehicles Oil Filter (PF64)',
    description: 'Oil filter for GM vehicles. Part No. PF64. High-filtration capacity for extended engine life.',
    price: 52,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'PF64',
    inStock: true,
  },
  {
    id: '6',
    slug: 'ford-vehicles-oil-filter-bb3q674ba',
    name: 'Ford Vehicles Oil Filter (BB3Q674BA)',
    description: 'Oil filter for Ford vehicles. Part No. BB3Q674BA. Genuine-quality replacement for Ford models.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'BB3Q674BA',
    inStock: true,
  },
  {
    id: '7',
    slug: 'nissan-vehicles-oil-filter-15208-65f0a',
    name: 'Nissan Vehicles Oil Filter (15208-65F0A)',
    description: 'Oil filter for Nissan vehicles. Part No. 15208-65F0A. Designed to OEM specifications.',
    price: 29,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '15208-65F0A',
    inStock: true,
  },
  {
    id: '8',
    slug: 'honda-vehicles-oil-filter-15400-plm-a02',
    name: 'Honda Vehicles Oil Filter (15400-PLM-A02)',
    description: 'Oil filter for Honda vehicles. Part No. 15400-PLM-A02. Ideal for various Honda engine types.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '15400-PLM-A02',
    inStock: true,
  },
  {
    id: '9',
    slug: 'isuzu-dmax-oil-filter-8-98165071-t',
    name: 'Isuzu D-Max Oil Filter (8-98165071-T)',
    description: 'Oil filter for Isuzu D-Max. Part No. 8-98165071-T. Heavy-duty filtration for D-Max diesel engines.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '8-98165071-T',
    inStock: true,
  },
  {
    id: '10',
    slug: 'mitsubishi-l200-oil-filter-md069782',
    name: 'Mitsubishi L200 Oil Filter (MD069782)',
    description: 'Oil filter for Mitsubishi L200 pickup. Part No. MD069782. Ensures engine durability on the L200.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'MD069782',
    inStock: true,
  },
  {
    id: '11',
    slug: 'toyota-vehicles-oil-filter-90915-yzzd4',
    name: 'Toyota Vehicles Oil Filter (90915-YZZD4)',
    description: 'Oil filter for Toyota vehicles. Part No. 90915-YZZD4. Compatible with multiple Toyota models.',
    price: 49,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '90915-YZZD4',
    inStock: true,
  },
  {
    id: '12',
    slug: 'mitsubishi-pajero-oil-filter-1230a182',
    name: 'Mitsubishi Pajero Oil Filter (1230A182)',
    description: 'Oil filter for Mitsubishi Pajero. Part No. 1230A182. OEM-grade replacement for Pajero engines.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '1230A182',
    inStock: true,
  },
  {
    id: '13',
    slug: 'hyundai-vehicles-oil-filter-26300-35505',
    name: 'Hyundai Vehicles Oil Filter (26300-35505)',
    description: 'Oil filter for Hyundai vehicles. Part No. 26300-35505. Fits a wide range of Hyundai models.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '26300-35505',
    inStock: true,
  },
  {
    id: '14',
    slug: 'toyota-vehicles-oil-filter-04145-37010',
    name: 'Toyota Vehicles Oil Filter (04145-37010)',
    description: 'Oil filter for Toyota vehicles. Part No. 04145-37010. Maintains oil purity for Toyota engines.',
    price: 29,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '04145-37010',
    inStock: true,
  },
  {
    id: '15',
    slug: 'toyota-vehicles-oil-filter-0415-yzza1',
    name: 'Toyota Vehicles Oil Filter (0415-YZZA1)',
    description: 'Oil filter for Toyota vehicles. Part No. 0415-YZZA1. Quality engine protection for Toyota.',
    price: 29,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '0415-YZZA1',
    inStock: true,
  },
  {
    id: '16',
    slug: 'toyota-vehicles-oil-filter-91915-yzzei',
    name: 'Toyota Vehicles Oil Filter (91915-YZZEI)',
    description: 'Oil filter for Toyota vehicles. Part No. 91915-YZZEI. Ensures long-lasting engine cleanliness.',
    price: 29,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '91915-YZZEI',
    inStock: true,
  },
  {
    id: '17',
    slug: 'toyota-vehicles-oil-filter-0415-yzza4',
    name: 'Toyota Vehicles Oil Filter (0415-YZZA4)',
    description: 'Oil filter for Toyota vehicles. Part No. 0415-YZZA4. Reliable filtration for Toyota petrol engines.',
    price: 65,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '0415-YZZA4',
    inStock: true,
  },
  {
    id: '18',
    slug: 'toyota-vehicles-oil-filter-90915-yzze2',
    name: 'Toyota Vehicles Oil Filter (90915-YZZE2)',
    description: 'Oil filter for Toyota vehicles. Part No. 90915-YZZE2. Prevents contaminants from entering the engine.',
    price: 29,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '90915-YZZE2',
    inStock: true,
  },

  // ─── Air Filters ────────────────────────────────────────────────────────────
  {
    id: '19',
    slug: 'renault-duster-air-filter-165467674r',
    name: 'Renault Duster Air Filter (165467674R)',
    description: 'Air filter for Renault Duster. Part No. 165467674R. Keeps engine air clean for optimal Duster performance.',
    price: 104,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '165467674R',
    inStock: true,
  },
  {
    id: '20',
    slug: 'rav4-highlander-air-filter-17801-25020',
    name: 'Toyota RAV4 / Highlander Air Filter (17801-25020)',
    description: 'Air filter for Toyota RAV4 and Highlander. Part No. 17801-25020. OEM-compatible fit for multiple Toyota SUVs.',
    price: 62,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-25020',
    inStock: true,
  },
  {
    id: '21',
    slug: 'lc-prado-2-8l-air-filter-17801-11130',
    name: 'LC Prado 2.8L Air Filter (17801-11130)',
    description: 'Air filter for Toyota Land Cruiser Prado 2.8L. Part No. 17801-11130. Heavy-duty engine air protection.',
    price: 72,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-11130',
    inStock: true,
  },
  {
    id: '22',
    slug: 'prado-2-7l-air-filter-17801-30040',
    name: 'Prado 2.7L Air Filter (17801-30040)',
    description: 'Air filter for Toyota Prado 2.7L. Part No. 17801-30040. Ensures clean airflow for the Prado engine.',
    price: 72,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-30040',
    inStock: true,
  },
  {
    id: '23',
    slug: 'rav4-avalon-air-filter-17801-77050',
    name: 'Toyota RAV4 / Avalon Air Filter (17801-77050)',
    description: 'Air filter for Toyota RAV4 and Avalon. Part No. 17801-77050. Premium airflow filtration for Toyota engines.',
    price: 59,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-77050',
    inStock: true,
  },
  {
    id: '24',
    slug: 'corolla-yaris-air-filter-17801-21050',
    name: 'Corolla / Yaris Air Filter (17801-21050)',
    description: 'Air filter for Toyota Corolla (2018+) and Yaris. Part No. 17801-21050. Compact and efficient engine air filter.',
    price: 46,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-21050',
    inStock: true,
  },
  {
    id: '25',
    slug: 'landcruiser-v8-air-filter-17801-51020',
    name: 'Land Cruiser V8 Air Filter (17801-51020)',
    description: 'Air filter for Toyota Land Cruiser V8. Part No. 17801-51020. Designed for high-displacement V8 engine demands.',
    price: 104,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-51020',
    inStock: true,
  },
  {
    id: '26',
    slug: 'nissan-hard-body-air-filter-1654-vk500',
    name: 'Nissan Hard Body Air Filter (1654-VK500)',
    description: 'Air filter for Nissan Hard Body. Part No. 1654-VK500. Durable filtration for Nissan workhorse trucks.',
    price: 104,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '1654-VK500',
    inStock: true,
  },
  {
    id: '27',
    slug: 'ford-bronco-air-filter-mb3g960iaa',
    name: 'Ford Bronco Air Filter (MB3G960IAA)',
    description: 'Air filter for Ford Bronco. Part No. MB3G960IAA. High-performance filtration for the Bronco engine.',
    price: 195,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'MB3G960IAA',
    inStock: true,
  },
  {
    id: '28',
    slug: 'fiat-tipo-air-filter-52069663',
    name: 'Fiat Tipo Air Filter (52069663)',
    description: 'Air filter for Fiat Tipo. Part No. 52069663. Maintains engine efficiency on the Fiat Tipo.',
    price: 104,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '52069663',
    inStock: true,
  },
  {
    id: '29',
    slug: 'isuzu-dmax-air-filter-8981402660',
    name: 'Isuzu D-Max Air Filter (8981402660)',
    description: 'Air filter for Isuzu D-Max. Part No. 8981402660. Durable air filtration for D-Max diesel engines.',
    price: 104,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '8981402660',
    inStock: true,
  },
  {
    id: '30',
    slug: 'hyundai-accent-air-filter-28113yr100',
    name: 'Hyundai Accent Air Filter (28113YR100)',
    description: 'Air filter for Hyundai Accent. Part No. 28113YR100. Keeps the Accent engine breathing clean air.',
    price: 46,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '28113YR100',
    inStock: true,
  },
  {
    id: '31',
    slug: 'honda-civic-air-filter-17220-a00',
    name: 'Honda Civic Air Filter (17220-A00)',
    description: 'Air filter for Honda Civic. Part No. 17220-A00. OEM-compatible engine air filtration for Civic models.',
    price: 72,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17220-A00',
    inStock: true,
  },
  {
    id: '32',
    slug: 'honda-accord-air-filter-17220-6b2-a00',
    name: 'Honda Accord Air Filter (17220-6B2-A00)',
    description: 'Air filter for Honda Accord. Part No. 17220-6B2-A00. Precise fit for Accord engine air intake.',
    price: 72,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17220-6B2-A00',
    inStock: true,
  },
  {
    id: '33',
    slug: 'honda-civic-crv-air-filter-17200-5ba-a00',
    name: 'Honda Civic / CR-V Air Filter (17200-5BA-A00)',
    description: 'Air filter for Honda Civic and CR-V. Part No. 17200-5BA-A00. Multi-model Honda air filtration.',
    price: 72,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17200-5BA-A00',
    inStock: true,
  },
  {
    id: '34',
    slug: 'honda-civic-16-25-air-filter-17220-5ba-a00',
    name: "Honda Civic '16-'25 Air Filter (17220-5BA-A00)",
    description: "Air filter for Honda Civic 2016–2025. Part No. 17220-5BA-A00. Fits the latest Honda Civic generations.",
    price: 72,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17220-5BA-A00',
    inStock: true,
  },
  {
    id: '35',
    slug: 'toyota-hilux-air-filter-17801-0l040',
    name: 'Toyota Hilux Air Filter (17801-0L040)',
    description: 'Air filter for Toyota Hilux. Part No. 17801-0L040. Robust filtration for Hilux diesel engines.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-0L040',
    inStock: true,
  },

  // ─── Fuel Filters ───────────────────────────────────────────────────────────
  {
    id: '36',
    slug: 'ford-ranger-fuel-filter-ab399176ac',
    name: 'Ford Ranger Fuel Filter (AB399176AC)',
    description: 'Fuel filter for Ford Ranger. Part No. AB399176AC. Ensures clean fuel delivery to the Ranger engine.',
    price: 52,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'AB399176AC',
    inStock: true,
  },
  {
    id: '37',
    slug: 'toyota-landcruiser-300-fuel-filter-23390-52060',
    name: 'Toyota Land Cruiser 300 Fuel Filter (23390-52060)',
    description: 'Fuel filter for Toyota Land Cruiser 300 Series. Part No. 23390-52060. Premium fuel protection for the LC300.',
    price: 130,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-52060',
    inStock: true,
  },
  {
    id: '38',
    slug: 'toyota-hilux-570-fuel-filter-23390-51030',
    name: 'Toyota Hilux 570 Fuel Filter (23390-51030)',
    description: 'Fuel filter for Toyota Hilux 570 series. Part No. 23390-51030. Keeps fuel injection clean on the Hilux.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-51030',
    inStock: true,
  },
  {
    id: '39',
    slug: 'toyota-hilux-fortuner-fuel-filter-23390-0l090',
    name: 'Toyota Hilux / Fortuner Fuel Filter (23390-0L090)',
    description: 'Fuel filter for Toyota Hilux and Fortuner. Part No. 23390-0L090. Dual-application fuel system protection.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-0L090',
    inStock: true,
  },
  {
    id: '40',
    slug: 'toyota-hilux-570-fuel-filter-23390-0l041',
    name: 'Toyota Hilux 570 Fuel Filter (23390-0L041)',
    description: 'Fuel filter for Toyota Hilux 570. Part No. 23390-0L041. Consistent fuel filtration for the Hilux diesel.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-0L041',
    inStock: true,
  },
  {
    id: '41',
    slug: 'toyota-lc-prado-patrol-fuel-filter-23300-75140',
    name: 'Toyota LC Prado / Patrol Fuel Filter (23300-75140)',
    description: 'Fuel filter for Toyota LC Prado and Patrol. Part No. 23300-75140. Dual-application off-road fuel protection.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23300-75140',
    inStock: true,
  },
  {
    id: '42',
    slug: 'toyota-lc-v8-fuel-filter-23390-51070',
    name: 'Toyota LC V8 Fuel Filter (23390-51070)',
    description: 'Fuel filter for Toyota Land Cruiser V8. Part No. 23390-51070. High-capacity fuel filtration for V8 engines.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-51070',
    inStock: true,
  },
  {
    id: '43',
    slug: 'mitsubishi-l200-fuel-filter-1770a337',
    name: 'Mitsubishi L200 Fuel Filter (1770A337)',
    description: 'Fuel filter for Mitsubishi L200. Part No. 1770A337. Protects the L200 fuel injection system from contaminants.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '1770A337',
    inStock: true,
  },
  {
    id: '44',
    slug: 'toyota-lc-prado-fuel-filter-23303-64010',
    name: 'Toyota LC Prado Fuel Filter (23303-64010)',
    description: 'Fuel filter for Toyota Land Cruiser Prado. Part No. 23303-64010. Essential maintenance part for the Prado.',
    price: 78,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23303-64010',
    inStock: true,
  },

  // ─── A/C Filters ────────────────────────────────────────────────────────────
  {
    id: '45',
    slug: 'honda-vehicles-ac-filter-80219-tf3-e01',
    name: 'Honda Vehicles A/C Filter (80219-TF3-E01)',
    description: 'Cabin A/C filter for Honda vehicles. Part No. 80219-TF3-E01. Improves in-cabin air quality for Honda models.',
    price: 46,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '80219-TF3-E01',
    inStock: true,
  },
  {
    id: '46',
    slug: 'ford-ranger-ac-filter-ab39-19n19-a',
    name: 'Ford Ranger A/C Filter (AB39-19N19-A)',
    description: 'Cabin A/C filter for Ford Ranger. Part No. AB39-19N19-A. Filters dust and pollen from cabin air.',
    price: 46,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'AB39-19N19-A',
    inStock: true,
  },
  {
    id: '47',
    slug: 'isuzu-dmax-ac-filter-8-98139428-0',
    name: 'Isuzu D-Max A/C Filter (8-98139428-0)',
    description: 'Cabin A/C filter for Isuzu D-Max. Part No. 8-98139428-0. Keeps D-Max cabin air fresh and clean.',
    price: 46,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '8-98139428-0',
    inStock: true,
  },
  {
    id: '48',
    slug: 'toyota-vehicles-ac-filter-87139-50100',
    name: 'Toyota Vehicles A/C Filter (87139-50100)',
    description: 'Cabin A/C filter for Toyota vehicles. Part No. 87139-50100. Compatible with multiple Toyota models.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '87139-50100',
    inStock: true,
  },
  {
    id: '49',
    slug: 'toyota-vehicles-ac-filter-87139-0k070',
    name: 'Toyota Vehicles A/C Filter (87139-0K070)',
    description: 'Cabin A/C filter for Toyota vehicles. Part No. 87139-0K070. Essential for clean cabin air circulation.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '87139-0K070',
    inStock: true,
  },
  {
    id: '50',
    slug: 'toyota-vehicles-ac-filter-87139-0n010',
    name: 'Toyota Vehicles A/C Filter (87139-0N010)',
    description: 'Cabin A/C filter for Toyota vehicles. Part No. 87139-0N010. Traps fine dust and allergens effectively.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '87139-0N010',
    inStock: true,
  },
  {
    id: '51',
    slug: 'toyota-vehicles-ac-filter-87131-06060',
    name: 'Toyota Vehicles A/C Filter (87131-06060)',
    description: 'Cabin A/C filter for Toyota vehicles. Part No. 87131-06060. OEM-grade in-cabin air filtration for Toyota.',
    price: 39,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '87131-06060',
    inStock: true,
  },

  // ─── Front Brake Pads ───────────────────────────────────────────────────────
  {
    id: '52',
    slug: 'toyota-lc-v8-front-brake-pad-d1303',
    name: 'Toyota LC V8 Front Brake Pad (D1303)',
    description: 'Front brake pads for Toyota Land Cruiser V8. Part No. D1303. High-grade stopping power for heavy V8 SUVs.',
    price: 390,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1303',
    inStock: true,
  },
  {
    id: '53',
    slug: 'toyota-prado-fortuner-front-brake-pad-d976',
    name: 'Toyota Prado / Fortuner Front Brake Pad (D976)',
    description: 'Front brake pads for Toyota Prado and Fortuner. Part No. D976. Low-dust, quiet braking for Toyota SUVs.',
    price: 325,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D976',
    inStock: true,
  },
  {
    id: '54',
    slug: 'toyota-lc-300-front-brake-pad-td1270',
    name: 'Toyota LC 300 Front Brake Pad (TD1270)',
    description: 'Front brake pads for Toyota Land Cruiser 300. Part No. TD1270. Premium braking for the LC300 platform.',
    price: 494,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TD1270',
    inStock: true,
  },
  {
    id: '55',
    slug: 'ford-f150-front-brake-pad-d1414',
    name: 'Ford F150 Front Brake Pad (D1414)',
    description: 'Front brake pads for Ford F-150. Part No. D1414. Heavy-duty braking for the Ford F-150 pickup truck.',
    price: 494,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1414',
    inStock: true,
  },
  {
    id: '56',
    slug: 'dodge-ram-r1500-front-brake-pad-d1084',
    name: 'Dodge Ram R1500 Front Brake Pad (D1084)',
    description: 'Front brake pads for Dodge Ram R1500. Part No. D1084. Reliable stopping performance for the Ram 1500.',
    price: 494,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1084',
    inStock: true,
  },
  {
    id: '57',
    slug: 'chevrolet-gm-front-brake-pad-d1363',
    name: 'Chevrolet GM Vehicle Front Brake Pad (D1363)',
    description: 'Front brake pads for Chevrolet and GM vehicles. Part No. D1363. OEM-grade brake performance for GM SUVs and trucks.',
    price: 494,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1363',
    inStock: true,
  },
  {
    id: '58',
    slug: 'honda-crv-front-brake-pad-d2036',
    name: 'Honda CR-V Front Brake Pad (D2036)',
    description: 'Front brake pads for Honda CR-V. Part No. D2036. Quiet and reliable braking for the Honda CR-V.',
    price: 325,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D2036',
    inStock: true,
  },
  {
    id: '59',
    slug: 'honda-civic-front-brake-pad-d914',
    name: 'Honda Civic Front Brake Pad (D914)',
    description: 'Front brake pads for Honda Civic. Part No. D914. Low-noise formula for smooth Civic braking.',
    price: 325,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D914',
    inStock: true,
  },
  {
    id: '60',
    slug: 'honda-accord-front-brake-pad-d1654',
    name: 'Honda Accord Front Brake Pad (D1654)',
    description: 'Front brake pads for Honda Accord. Part No. D1654. Confident braking performance for the Accord.',
    price: 325,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1654',
    inStock: true,
  },
  {
    id: '61',
    slug: 'isuzu-dmax-front-brake-pad-td1499',
    name: 'Isuzu D-Max Front Brake Pad (TD1499)',
    description: 'Front brake pads for Isuzu D-Max. Part No. TD1499. Heavy-duty braking built for the D-Max workhorse.',
    price: 390,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TD1499',
    inStock: true,
  },
  {
    id: '62',
    slug: 'ford-ranger-front-brake-pad-ab3z-2v001a',
    name: 'Ford Ranger Front Brake Pad (AB3Z-2V001A)',
    description: 'Front brake pads for Ford Ranger. Part No. AB3Z-2V001A. Dependable brake performance for Ranger trucks.',
    price: 325,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'AB3Z-2V001A',
    inStock: true,
  },
  {
    id: '63',
    slug: 'mitsubishi-l200-front-brake-pad-4605a284',
    name: 'Mitsubishi L200 Front Brake Pad (4605A284)',
    description: 'Front brake pads for Mitsubishi L200. Part No. 4605A284. Durable and effective braking for the L200.',
    price: 260,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '4605A284',
    inStock: true,
  },
  {
    id: '64',
    slug: 'toyota-rav4-front-brake-pad-d2076',
    name: 'Toyota RAV4 Front Brake Pad (D2076)',
    description: 'Front brake pads for Toyota RAV4. Part No. D2076. Precise fit and reliable stopping for the RAV4.',
    price: 260,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D2076',
    inStock: true,
  },

  // ─── Rear Brake Pads ────────────────────────────────────────────────────────
  {
    id: '65',
    slug: 'toyota-lc-v8-rear-brake-pad-d1304',
    name: 'Toyota LC V8 Rear Brake Pad (D1304)',
    description: 'Rear brake pads for Toyota Land Cruiser V8. Part No. D1304. Balanced braking for heavy V8 Land Cruisers.',
    price: 260,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1304',
    inStock: true,
  },
  {
    id: '66',
    slug: 'toyota-lc-300-rear-brake-pad-d2439',
    name: 'Toyota LC 300 Rear Brake Pad (D2439)',
    description: 'Rear brake pads for Toyota Land Cruiser 300. Part No. D2439. Consistent rear braking for the LC300.',
    price: 325,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D2439',
    inStock: true,
  },
  {
    id: '67',
    slug: 'toyota-rav4-rear-brake-pad-d1879',
    name: 'Toyota RAV4 Rear Brake Pad (D1879)',
    description: 'Rear brake pads for Toyota RAV4. Part No. D1879. Quiet and effective rear braking for the RAV4.',
    price: 195,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1879',
    inStock: true,
  },
  {
    id: '68',
    slug: 'honda-civic-rear-brake-pad-d1878',
    name: 'Honda Civic Rear Brake Pad (D1878)',
    description: 'Rear brake pads for Honda Civic. Part No. D1878. Low-dust formula for clean, quiet Civic rear braking.',
    price: 195,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1878',
    inStock: true,
  },
  {
    id: '69',
    slug: 'honda-crv-rear-brake-pad-d2037',
    name: 'Honda CR-V Rear Brake Pad (D2037)',
    description: 'Rear brake pads for Honda CR-V. Part No. D2037. Smooth and reliable rear braking for the CR-V.',
    price: 195,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D2037',
    inStock: true,
  },
  {
    id: '70',
    slug: 'lc-prado-2-8l-rear-brake-pad-d606',
    name: 'LC Prado 2.8L Rear Brake Pad (D606)',
    description: 'Rear brake pads for Toyota Land Cruiser Prado 2.8L. Part No. D606. Solid rear braking for the Prado 2.8L.',
    price: 234,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D606',
    inStock: true,
  },

  // ─── Food & Beverages ───────────────────────────────────────────────────────
  {
    id: '71',
    slug: 'premium-vegetable-oil-5l',
    name: 'Premium Vegetable Oil 5L',
    description: 'High-quality vegetable cooking oil ideal for retail distribution. Suitable for cooking, frying, and food preparation.',
    price: 45,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'FMCG-001',
    inStock: true,
  },
  {
    id: '72',
    slug: 'rice-5kg',
    name: 'Rice 5kg',
    description: 'Premium quality rice in a convenient 5kg pack. Clean, well-processed grains. Perfect for households and small retailers.',
    price: 88,
    currency: 'GHS',
    image: '/images/rice-pic.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'FMCG-RICE-5KG',
    inStock: true,
    featured: true,
    tags: ['featured', 'rice', 'food'],
  },
  {
    id: '73',
    slug: 'rice-30kg',
    name: 'Rice 30kg',
    description: 'Premium quality rice in a 30kg wholesale bag. Clean, well-processed grains ideal for bulk buyers, retailers and caterers.',
    price: 510,
    currency: 'GHS',
    image: '/images/rice-pic.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'FMCG-RICE-30KG',
    inStock: true,
    featured: true,
    tags: ['featured', 'rice', 'food'],
  },

  // ─── Electronics ────────────────────────────────────────────────────────────
  {
    id: '74',
    slug: 'led-bulb-12w',
    name: 'LED Bulb 12W',
    description: 'Energy-efficient 12W LED bulb with long lifespan. Perfect for home and office use.',
    price: 18,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'ELEC-001',
    inStock: true,
  },
  {
    id: '75',
    slug: 'rechargeable-flashlight',
    name: 'Rechargeable Flashlight',
    description: 'Durable rechargeable flashlight with LED technology. Ideal for homes and security.',
    price: 45,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'ELEC-002',
    inStock: true,
  },
  {
    id: '76',
    slug: 'mobile-phone-charger',
    name: 'Mobile Phone Charger',
    description: 'Universal USB charger compatible with most smartphones. Fast charging capability.',
    price: 22,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'ELEC-003',
    inStock: true,
  },

  // ─── Fabrics ─────────────────────────────────────────────────────────────────
  {
    id: '77',
    slug: 'cotton-print-fabric',
    name: 'Cotton Print Fabric',
    description: 'High-quality printed cotton fabric for tailoring and fashion. Vibrant colors and patterns.',
    price: 55,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.FABRICS,
    sku: 'FAB-001',
    inStock: true,
  },
  {
    id: '78',
    slug: 'ankara-wax-print',
    name: 'Ankara Wax Print',
    description: 'Authentic African wax print fabric. Perfect for traditional wear and fashion design.',
    price: 65,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.FABRICS,
    sku: 'FAB-002',
    inStock: true,
  },

  // ─── Agricultural Inputs ────────────────────────────────────────────────────
  {
    id: '79',
    slug: 'npk-fertilizer-50kg',
    name: 'NPK Fertilizer 50kg',
    description: 'Balanced NPK fertilizer for crop enhancement. Suitable for various agricultural applications.',
    price: 220,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AGRIC_INPUTS,
    sku: 'AGRI-001',
    inStock: true,
  },
  {
    id: '80',
    slug: 'herbicide-concentrate',
    name: 'Herbicide Concentrate',
    description: 'Effective herbicide for weed control in farms. Safe for crops when used as directed.',
    price: 150,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AGRIC_INPUTS,
    sku: 'AGRI-002',
    inStock: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getAllProducts(): Product[] {
  return PRODUCTS;
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}
