/**
 * Product data for commerce (build-time static).
 * Replace with CMS or API later if needed.
 */

// Product categories
export const PRODUCT_CATEGORIES = {
  FMCG: 'FMCG',
  AUTOPARTS: 'Autoparts',
  ELECTRONICS: 'Electronics',
  FABRICS: 'Fabrics',
  AGRIC_INPUTS: 'Agricultural Inputs',
} as const;

export type ProductCategory = typeof PRODUCT_CATEGORIES[keyof typeof PRODUCT_CATEGORIES];

export type Product = {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;          // Use 0 for "Price on Request"
  currency: string;       // "GHS"
  image: string;
  category: string;       // Required - one of PRODUCT_CATEGORIES
  sku?: string;           // Optional SKU for inventory tracking
  inStock?: boolean;      // Optional stock status (default true)
  tags?: string[];        // Optional tags for filtering
};

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'toyota-vehicles-oil-filter-highlander-sienna-rav4-camry-etc',
    name: 'Toyota Vehicles Oil Filter (Highlander, Sienna, Rav4, Camry etc.)',
    description: 'Essential oil filter compatible with a wide range of Toyota models. High-efficiency filtration.',
    price: 35,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-OF-001',
    inStock: true,
  },
  {
    id: '2',
    slug: 'oil-filter-toyota-corolla-matrix-c-hr-lexus-ls-is-etc',
    name: 'Oil Filter Toyota Corolla, Matrix, C-HR, Lexus LS, IS etc.',
    description: 'Oil filter specifically designed for smaller engine Toyota and Lexus models. OEM specifications.',
    price: 32,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-OF-002',
    inStock: true,
  },
  {
    id: '3',
    slug: 'toyota-corolla-air-filter',
    name: 'Toyota Corolla Air Filter',
    description: 'High-flow air filter for Toyota Corolla models. Improves engine performance and efficiency.',
    price: 25,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-AF-001',
    inStock: true,
  },
  {
    id: '4',
    slug: 'land-cruiser-200-v8-air-filter',
    name: 'Land Cruiser 200, V8 Air Filter',
    description: 'Heavy-duty air filter for Toyota Land Cruiser 200 Series V8 engines. Durable and long-lasting.',
    price: 45,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-AF-001',
    inStock: true,
  },
  {
    id: '5',
    slug: 'toyota-rav4-air-filter',
    name: 'Toyota Rav4 Air Filter',
    description: 'Air filter designed to fit various Toyota RAV4 generations. Protects engine from contaminants.',
    price: 28,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-AF-002',
    inStock: true,
  },
  {
    id: '6',
    slug: 'toyota-hilux-air-filter',
    name: 'Toyota Hilux Air Filter',
    description: 'Robust air filter for Toyota Hilux pickup trucks. Suitable for harsh driving conditions.',
    price: 30,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-AF-003',
    inStock: true,
  },
  {
    id: '7',
    slug: 'toyota-highlander-rav4-air-filter',
    name: 'Toyota Highlander, RAV4 Air Filter',
    description: 'Standard air filter compatible with Toyota Highlander and certain RAV4 models.',
    price: 29,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-AF-004',
    inStock: true,
  },
  {
    id: '8',
    slug: 'toyota-hilux-fortuner-fuel-filter',
    name: 'Toyota Hilux, Fortuner Fuel Filter',
    description: 'High-quality fuel filter for Toyota Hilux and Fortuner models. Ensures clean fuel delivery.',
    price: 40,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-FF-001',
    inStock: true,
  },
  {
    id: '9',
    slug: 'toyota-land-cruiser-prado-fuel-filter',
    name: 'Toyota Land Cruiser Prado Fuel Filter',
    description: 'Fuel filter for Land Cruiser Prado models. Essential for protecting the fuel injection system.',
    price: 48,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-FF-001',
    inStock: true,
  },
  {
    id: '10',
    slug: 'toyota-land-cruiser-v8-fuel-filter',
    name: 'Toyota Land Cruiser V8 Fuel Filter',
    description: 'Heavy-duty fuel filter for Land Cruiser V8 engines. High filtration capacity.',
    price: 55,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-FF-002',
    inStock: true,
  },
  {
    id: '11',
    slug: 'toyota-land-cruiser-fuel-filter',
    name: 'Toyota Land Cruiser Fuel Filter',
    description: 'Universal or general fuel filter for various Land Cruiser models.',
    price: 45,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-FF-003',
    inStock: true,
  },
  {
    id: '12',
    slug: 'toyota-land-cruiser-300-70th-anniversary-front-brake-pad',
    name: 'Toyota Land Cruiser 300 70th Anniversary Front Brake Pad',
    description: 'Premium front brake pads for the Land Cruiser 300 Series (70th Anniversary Edition).',
    price: 120,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-BPF-001',
    inStock: true,
  },
  {
    id: '13',
    slug: 'toyota-land-cruiser-300-70th-anniversary-rear-brake-pad',
    name: 'Toyota Land Cruiser 300 70th Anniversary Rear Brake Pad',
    description: 'Premium rear brake pads for the Land Cruiser 300 Series (70th Anniversary Edition).',
    price: 110,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-BPR-001',
    inStock: true,
  },
  {
    id: '14',
    slug: 'land-cruiser-200-v8-front-brake-pad',
    name: 'Land Cruiser 200 V8 Front Brake Pad',
    description: 'High-performance front brake pads for Land Cruiser 200 Series V8. Excellent stopping power.',
    price: 95,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-BPF-002',
    inStock: true,
  },
  {
    id: '15',
    slug: 'land-cruiser-200-v8-rear-brake-pad',
    name: 'Land Cruiser 200 V8 Rear Brake Pad',
    description: 'High-performance rear brake pads for Land Cruiser 200 Series V8.',
    price: 88,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-BPR-002',
    inStock: true,
  },
  {
    id: '16',
    slug: 'toyota-hilux-prado-fortuner-front-brake-pad',
    name: 'Toyota Hilux, Prado, Fortuner Front Brake Pad',
    description: 'Durable front brake pads for Toyota Hilux, Prado, and Fortuner. Reliable performance.',
    price: 80,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-BPF-001',
    inStock: true,
  },
  {
    id: '17',
    slug: 'toyota-hilux-prado-fortuner-rear-brake-pad',
    name: 'Toyota Hilux, Prado, Fortuner Rear Brake Pad',
    description: 'Durable rear brake pads for Toyota Hilux, Prado, and Fortuner.',
    price: 75,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TOY-BPR-001',
    inStock: true,
  },
  {
    id: '18',
    slug: 'toyota-rav4-2018-front-brake-pad',
    name: 'Toyota Rav4 (2018+) Front Brake Pad',
    description: 'Front brake pads for Toyota RAV4 2018 model and newer. Low dust, low noise formula.',
    price: 65,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'RAV-BPF-001',
    inStock: true,
  },
  {
    id: '19',
    slug: 'toyota-rav4-rear-brake-pads',
    name: 'Toyota Rav4 Rear Brake Pads',
    description: 'Rear brake pads for Toyota RAV4 models.',
    price: 60,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'RAV-BPR-001',
    inStock: true,
  },
  {
    id: '20',
    slug: 'mitsubishi-l200-oil-filter',
    name: 'Mitsubishi L200 Oil Filter',
    description: 'Oil filter for Mitsubishi L200 pickup. Ensures engine longevity.',
    price: 30,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'MIT-OF-001',
    inStock: true,
  },
  {
    id: '21',
    slug: 'fuel-filter-mitsubishi-l200',
    name: 'Fuel Filter Mitsubishi L200',
    description: 'Fuel filter for Mitsubishi L200. Protects against contaminants in the fuel system.',
    price: 38,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'MIT-FF-001',
    inStock: true,
  },
  {
    id: '22',
    slug: 'mitsubishi-l200-front-brake-pad',
    name: 'Mitsubishi L200 Front Brake Pad',
    description: 'Front brake pads for Mitsubishi L200. Offers reliable braking performance.',
    price: 70,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'MIT-BPF-001',
    inStock: true,
  },
  {
    id: '23',
    slug: 'toyota-land-cruiser-prado-air-filter-j150-2015-2024',
    name: 'Toyota Land Cruiser Prado Air Filter (J150, 2015-2024)',
    description: 'Air filter for Land Cruiser Prado J150 chassis (GDJ150, GDJ155 models).',
    price: 35,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-AF-002',
    inStock: true,
  },
  {
    id: '24',
    slug: 'oil-filter-gm-vehicles',
    name: 'Oil Filter GM Vehicles',
    description: 'General oil filter compatible with various General Motors (GM) vehicles.',
    price: 28,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'GM-OF-001',
    inStock: true,
  },
  {
    id: '25',
    slug: 'ford-ranger-diesel-oil-filter',
    name: 'Ford Ranger Diesel Oil Filter',
    description: 'Oil filter specifically for Ford Ranger diesel engines. High efficiency.',
    price: 33,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'FORD-OF-001',
    inStock: true,
  },
  {
    id: '26',
    slug: 'oil-filter-ford-vehicles',
    name: 'Oil Filter Ford Vehicles',
    description: 'General oil filter for a range of Ford gasoline vehicles.',
    price: 30,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'FORD-OF-002',
    inStock: true,
  },
  {
    id: '27',
    slug: 'oil-filter-hyundai-vehicles',
    name: 'Oil Filter Hyundai Vehicles',
    description: 'Oil filter compatible with various Hyundai models.',
    price: 25,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HYU-OF-001',
    inStock: true,
  },
  {
    id: '28',
    slug: 'honda-vehicles-oil-filter',
    name: 'Honda Vehicles Oil Filter',
    description: 'Oil filter compatible with various Honda models.',
    price: 26,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-OF-001',
    inStock: true,
  },
  {
    id: '29',
    slug: 'oil-filter-ford-vehicles-for-honda-vehicles-all-models',
    name: 'Oil Filter Ford Vehicles For Honda Vehicles, All models',
    description: 'Multi-application oil filter for Ford and all Honda models.',
    price: 27,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'MUL-OF-001',
    inStock: true,
  },
  {
    id: '30',
    slug: 'air-filter-honda-civic-20l-2016-2025-hr-v-2023-2025',
    name: 'Air Filter Honda Civic 2.0L (2016-2025), HR-V (2023-2025)',
    description: 'Engine air filter for specific Honda Civic and HR-V models.',
    price: 22,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-AF-001',
    inStock: true,
  },
  {
    id: '31',
    slug: 'air-filter-honda-accord-20l-2018-2022',
    name: 'Air Filter Honda Accord 2.0L 2018-2022',
    description: 'Engine air filter for Honda Accord 2.0L models from 2018 to 2022.',
    price: 24,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-AF-002',
    inStock: true,
  },
  {
    id: '32',
    slug: 'air-filter-honda-cr-v-15l-2017-2022',
    name: 'Air Filter Honda CR-V 1.5L (2017-2022)',
    description: 'Engine air filter for Honda CR-V 1.5L models from 2017 to 2022.',
    price: 23,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-AF-003',
    inStock: true,
  },
  {
    id: '33',
    slug: 'air-filter-honda-civic-15l-2016-2022',
    name: 'Air Filter Honda Civic 1.5L (2016-2022)',
    description: 'Engine air filter for Honda Civic 1.5L models from 2016 to 2022.',
    price: 22,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-AF-004',
    inStock: true,
  },
  {
    id: '34',
    slug: 'air-filter-honda-civic-15l-22-24-crv-15l-23-24-integra-15l-23-24',
    name: 'Air Filter Honda Civic 1.5L (22-24), CRV 1.5L (23-24), Integra 1.5L (23-24)',
    description: 'Engine air filter for newer 1.5L Turbo Honda/Acura models.',
    price: 25,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-AF-005',
    inStock: true,
  },
  {
    id: '35',
    slug: 'honda-ac-filter',
    name: 'Honda AC Filter',
    description: 'Cabin air filter for various Honda models. Improves air quality inside the vehicle.',
    price: 18,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-ACF-001',
    inStock: true,
  },
  {
    id: '36',
    slug: 'honda-cr-v-front-brake-pad',
    name: 'Honda CR-V Front Brake Pad',
    description: 'Front brake pads for Honda CR-V. Reliable and quiet braking.',
    price: 60,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-BPF-001',
    inStock: true,
  },
  {
    id: '37',
    slug: 'honda-cr-v-rear-brake-pad',
    name: 'Honda CR-V Rear Brake Pad',
    description: 'Rear brake pads for Honda CR-V.',
    price: 55,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'HON-BPR-001',
    inStock: true,
  },
  {
    id: '38',
    slug: 'cadillac-escalade-avalanche-suburban-front-brake-pad-set-1',
    name: 'Cadillac Escalade, Avalanche, Suburban Front Brake Pad (Set 1)',
    description: 'Heavy-duty front brake pads for large GM SUVs and trucks.',
    price: 110,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'GM-BPF-001',
    inStock: true,
  },
  {
    id: '39',
    slug: 'ford-f-150-front-brake-pad',
    name: 'Ford F-150 Front Brake Pad',
    description: 'Front brake pads for the Ford F-150 truck. High performance and durability.',
    price: 90,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'FORD-BPF-001',
    inStock: true,
  },
  {
    id: '40',
    slug: 'dodge-ram-1500-front-brake-pad-set-1',
    name: 'Dodge Ram 1500 Front Brake Pad (Set 1)',
    description: 'Front brake pads for Dodge Ram 1500 pickup truck.',
    price: 85,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'DOD-BPF-001',
    inStock: true,
  },
  {
    id: '41',
    slug: 'toyota-land-cruiser-v8-oil-filter',
    name: 'Toyota Land Cruiser V8 Oil Filter',
    description: 'Oil filter for Land Cruiser V8 engines. High-quality replacement part.',
    price: 40,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'TLC-OF-001',
    inStock: true,
  },
  {
    id: '42',
    slug: 'automotive-oil-filter',
    name: 'Automotive Oil Filter',
    description: 'Compatible oil filter for major vehicle brands. OEM quality replacement part.',
    price: 35.5,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'SP-001',
    inStock: true,
  },
  {
    id: '43',
    slug: 'brake-pads-set',
    name: 'Brake Pads Set',
    description: 'High-quality brake pads for passenger vehicles. Reliable stopping power and long-lasting performance.',
    price: 90,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'SP-002',
    inStock: true,
  },
  {
    id: '44',
    slug: 'wiper-blades-pair',
    name: 'Wiper Blades Pair',
    description: 'Universal wiper blades compatible with most vehicles. Ensures clear visibility in rainy conditions.',
    price: 25,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'SP-003',
    inStock: true,
  },
  {
    id: '45',
    slug: 'premium-vegetable-oil-5l',
    name: 'Premium Vegetable Oil 5L',
    description: 'High-quality vegetable cooking oil ideal for retail distribution. Suitable for cooking, frying, and food preparation.',
    price: 45,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'FMCG-001',
    inStock: true,
  },
  {
    id: '46',
    slug: 'rice-25kg-bag',
    name: 'Rice 25kg Bag',
    description: 'Premium quality rice perfect for retail and wholesale distribution. Clean, well-processed grains.',
    price: 180,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'FMCG-002',
    inStock: true,
  },
  {
    id: '47',
    slug: 'led-bulb-12w',
    name: 'LED Bulb 12W',
    description: 'Energy-efficient 12W LED bulb with long lifespan. Perfect for home and office use.',
    price: 18,
    currency: 'GHS',
    image: '/images/services/service7.jpg',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'ELEC-001',
    inStock: true,
  },
  {
    id: '48',
    slug: 'rechargeable-flashlight',
    name: 'Rechargeable Flashlight',
    description: 'Durable rechargeable flashlight with LED technology. Ideal for homes and security.',
    price: 45,
    currency: 'GHS',
    image: '/images/services/service8.jpg',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'ELEC-002',
    inStock: true,
  },
  {
    id: '49',
    slug: 'mobile-phone-charger',
    name: 'Mobile Phone Charger',
    description: 'Universal USB charger compatible with most smartphones. Fast charging capability.',
    price: 22,
    currency: 'GHS',
    image: '/images/services/service1.jpg',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'ELEC-003',
    inStock: true,
  },
  {
    id: '50',
    slug: 'cotton-print-fabric',
    name: 'Cotton Print Fabric',
    description: 'High-quality printed cotton fabric for tailoring and fashion. Vibrant colors and patterns.',
    price: 55,
    currency: 'GHS',
    image: '/images/services/service2.jpg',
    category: PRODUCT_CATEGORIES.FABRICS,
    sku: 'FAB-001',
    inStock: true,
  },
  {
    id: '51',
    slug: 'ankara-wax-print',
    name: 'Ankara Wax Print',
    description: 'Authentic African wax print fabric. Perfect for traditional wear and fashion design.',
    price: 65,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.FABRICS,
    sku: 'FAB-002',
    inStock: true,
  },
  {
    id: '52',
    slug: 'npk-fertilizer-50kg',
    name: 'NPK Fertilizer 50kg',
    description: 'Balanced NPK fertilizer for crop enhancement. Suitable for various agricultural applications.',
    price: 220,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.AGRIC_INPUTS,
    sku: 'AGRI-001',
    inStock: true,
  },
  {
    id: '53',
    slug: 'herbicide-concentrate',
    name: 'Herbicide Concentrate',
    description: 'Effective herbicide for weed control in farms. Safe for crops when used as directed.',
    price: 150,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AGRIC_INPUTS,
    sku: 'AGRI-002',
    inStock: true,
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getAllProducts(): Product[] {
  return PRODUCTS;
}
