/**
 * Product data for commerce (build-time static).
 * Replace with CMS or API later if needed.
 */

// Product categories
export const PRODUCT_CATEGORIES = {
  FMCG: 'Food & Beverages',
  AUTOPARTS: 'Autoparts',
  ELECTRONICS: 'Electronics',
  FABRICS: 'Fabrics',
  AGRIC_INPUTS: 'Agricultural Inputs',
} as const;

export type ProductCategory = typeof PRODUCT_CATEGORIES[keyof typeof PRODUCT_CATEGORIES];

export type Product = {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;          // Use 0 for "Price on Request"
  currency: string;       // "GHS"
  image: string;
  category: string;       // Required - one of PRODUCT_CATEGORIES
  sku?: string;           // Optional SKU for inventory tracking
  inStock?: boolean;      // Optional stock status (default true)
  tags?: string[];        // Optional tags for filtering
  featured?: boolean;     // Featured product flag
};

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: '04152-37010-toyota-vehicles-oil-filter',
    name: '04152 37010 Toyota Vehicles Oil Filter',
    description: 'Reliable 04152 37010 Toyota Vehicles Oil Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/04152-37010-toyota-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-001',
    inStock: true,
  },
  {
    id: '2',
    slug: '04152-yzza1-toyota-vehicles-oil-filter',
    name: '04152 YZZA1 Toyota Vehicles Oil Filter',
    description: 'Reliable 04152 YZZA1 Toyota Vehicles Oil Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/04152-yzza1-toyota-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '04152-YZZA1',
    inStock: true,
  },
  {
    id: '3',
    slug: '15400-rta-003-honda-vehicles-oil-filter',
    name: '15400 RTA 003 Honda Vehicles Oil Filter',
    description: 'Reliable 15400 RTA 003 Honda Vehicles Oil Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/15400-rta-003-honda-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '15400-RTA-003',
    inStock: true,
  },
  {
    id: '4',
    slug: '17220-5aa-a00-honda-civic-air-filter',
    name: '17220 5AA A00 Honda Civic Air Filter',
    description: 'Reliable 17220 5AA A00 Honda Civic Air Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/17220-5aa-a00-honda-civic-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17220-5AA-A00',
    inStock: true,
  },
  {
    id: '5',
    slug: '17220-5ba-a00-honda-civic-crv-air-filter',
    name: '17220 5BA A00 Honda Civic CRV Air Filter',
    description: 'Reliable 17220 5BA A00 Honda Civic CRV Air Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/17220-5ba-a00-honda-civic-crv-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17220-5BA-A00',
    inStock: true,
  },
  {
    id: '6',
    slug: '17220-64a-a00-honda-air-filter',
    name: '17220 64A A00 Honda Air Filter',
    description: 'Reliable 17220 64A A00 Honda Air Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/17220-64a-a00-honda-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17220-64A-A00',
    inStock: true,
  },
  {
    id: '7',
    slug: '1770a338-mitsubishi-fuel-filter',
    name: '1770A338 Mitsubishi Fuel Filter',
    description: 'Reliable 1770A338 Mitsubishi Fuel Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/1770a338-mitsubishi-fuel-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '1770A338',
    inStock: true,
  },
  {
    id: '8',
    slug: '23390-0l070-toyota-lexus-fuel-filter',
    name: '23390 0L070 Toyota Lexus Fuel Filter',
    description: 'Reliable 23390 0L070 Toyota Lexus Fuel Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/23390-0l070-toyota-lexus-fuel-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-0L070',
    inStock: true,
  },
  {
    id: '9',
    slug: '80291-tf3-e01-honda-vehicles-ac-cabin-filter',
    name: '80291 TF3 E01 Honda Vehicles AC Cabin Filter',
    description: 'Reliable 80291 TF3 E01 Honda Vehicles AC Cabin Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/80291-tf3-e01-honda-vehicles-ac-cabin-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '80291-TF3-E01',
    inStock: true,
  },
  {
    id: '10',
    slug: '90915-yzze1-toyota-vehicles-oil-filter',
    name: '90915 YZZE1 Toyota Vehicles Oil Filter',
    description: 'Reliable 90915 YZZE1 Toyota Vehicles Oil Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/90915-yzze1-toyota-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '90915-YZZE1',
    inStock: true,
  },
  {
    id: '11',
    slug: 'african-black-soap-acne-n-blemish',
    name: 'African Black Soap Acne N Blemish',
    description: 'Reliable African Black Soap Acne N Blemish built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/african-black-soap-acne-n-blemish.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-002',
    inStock: true,
  },
  {
    id: '12',
    slug: 'african-black-soap-blossom',
    name: 'African Black Soap Blossom',
    description: 'Reliable African Black Soap Blossom built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/african-black-soap-blossom.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-003',
    inStock: true,
  },
  {
    id: '13',
    slug: 'african-black-soap-lemon-blast',
    name: 'African Black Soap Lemon Blast',
    description: 'Reliable African Black Soap Lemon Blast built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/african-black-soap-lemon-blast.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-004',
    inStock: true,
  },
  {
    id: '14',
    slug: 'african-black-soap-tropical-sunrise',
    name: 'African Black Soap Tropical Sunrise',
    description: 'Reliable African Black Soap Tropical Sunrise built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/african-black-soap-tropical-sunrise.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-005',
    inStock: true,
  },
  {
    id: '15',
    slug: 'bb3j6744ba-ford-vehicles-oil-filter',
    name: 'BB3J6744BA Ford Vehicles Oil Filter',
    description: 'Reliable BB3J6744BA Ford Vehicles Oil Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/bb3j6744ba-ford-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'BB3J6744BA',
    inStock: true,
  },
  {
    id: '16',
    slug: 'brake-pads-high-performance-generic',
    name: 'Brake Pads High Performance Generic',
    description: 'Reliable Brake Pads High Performance Generic built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/brake-pads-high-performance-generic.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-007',
    inStock: true,
  },
  {
    id: '17',
    slug: 'corolla-yaris-air-filter-17801-21050',
    name: 'Corolla / Yaris Air Filter (17801-21050)',
    description: 'Air filter for Toyota Corolla (2018+) and Yaris. Part No. 17801-21050. Compact and efficient engine air filter.',
    price: 46,
    currency: 'GHS',
    image: '/images/products/17801-21050-toyota-corolla-yaris-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-21050',
    inStock: true,
  },
  {
    id: '18',
    slug: 'egg-shell-opener-easy-clean-egg-cracking-tool',
    name: 'Egg Shell Opener – Easy & Clean Egg Cracking Tool',
    description: 'Reliable Egg Shell Opener – Easy & Clean Egg Cracking Tool built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/egg-shell-opener-easy-and-clean-egg-cracking-tool.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-009',
    inStock: true,
  },
  {
    id: '19',
    slug: 'egg-storage-container-and-egg-opener-value-pack',
    name: 'Egg Storage Container And Egg Opener Value Pack',
    description: 'Reliable Egg Storage Container And Egg Opener Value Pack built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/egg-storage-container-and-egg-opener-value-pack.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-010',
    inStock: true,
  },
  {
    id: '20',
    slug: 'ford-vehicles-oil-filter-fl500s',
    name: 'Ford Vehicles Oil Filter (FL500S)',
    description: 'Oil filter for Ford vehicles. Part No. FL500S. Reliable engine protection for Ford models.',
    price: 78,
    currency: 'GHS',
    image: '/images/products/fl-500s-ford-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'FL500S',
    inStock: true,
  },
  {
    id: '21',
    slug: 'ford-vehicles-oil-filter-fl910s',
    name: 'Ford Vehicles Oil Filter (FL910S)',
    description: 'Oil filter for Ford vehicles. Part No. FL910S. Ensures clean oil flow for optimal engine performance.',
    price: 49,
    currency: 'GHS',
    image: '/images/products/fl-910s-ford-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'FL910S',
    inStock: true,
  },
  {
    id: '22',
    slug: 'generic-brake-pads-red-box',
    name: 'Generic Brake Pads Red Box',
    description: 'Reliable Generic Brake Pads Red Box built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/generic-brake-pads-red-box.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-016',
    inStock: true,
  },
  {
    id: '23',
    slug: 'gm-vehicles-oil-filter-pf63e',
    name: 'GM Vehicles Oil Filter (PF63E)',
    description: 'High-efficiency oil filter for GM vehicles. Part No. PF63E. OEM-grade filtration for engine longevity.',
    price: 78,
    currency: 'GHS',
    image: '/images/products/pf63e-gm-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'PF63E',
    inStock: true,
  },
  {
    id: '24',
    slug: 'high-quality-ceramic-brake-pads',
    name: 'High Quality Ceramic Brake Pads',
    description: 'Reliable High Quality Ceramic Brake Pads built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/high-quality-ceramic-brake-pads.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-018',
    inStock: true,
  },
  {
    id: '25',
    slug: 'high-quality-ceramic-brake-pads-alt',
    name: 'High Quality Ceramic Brake Pads Alt',
    description: 'Reliable High Quality Ceramic Brake Pads Alt built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/high-quality-ceramic-brake-pads-alt.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-017',
    inStock: true,
  },
  {
    id: '26',
    slug: 'hoffman-air-fryer',
    name: 'Hoffman Air Fryer',
    description: 'Reliable Hoffman Air Fryer built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/hoffman-air-fryer.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-019',
    inStock: true,
  },
  {
    id: '27',
    slug: 'honda-accord-air-filter-17220-6b2-a00',
    name: 'Honda Accord Air Filter (17220-6B2-A00)',
    description: 'Air filter for Honda Accord. Part No. 17220-6B2-A00. Precise fit for Accord engine air intake.',
    price: 72,
    currency: 'GHS',
    image: '/images/products/17220-6b2-a00-honda-accord-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17220-6B2-A00',
    inStock: true,
  },
  {
    id: '28',
    slug: 'honda-vehicles-oil-filter-15400-plm-a02',
    name: 'Honda Vehicles Oil Filter (15400-PLM-A02)',
    description: 'Oil filter for Honda vehicles. Part No. 15400-PLM-A02. Ideal for various Honda engine types.',
    price: 39,
    currency: 'GHS',
    image: '/images/products/15400-plm-a02-honda-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '15400-PLM-A02',
    inStock: true,
  },
  {
    id: '29',
    slug: 'hyundai-vehicles-oil-filter-26300-35505',
    name: 'Hyundai Vehicles Oil Filter (26300-35505)',
    description: 'Oil filter for Hyundai vehicles. Part No. 26300-35505. Fits a wide range of Hyundai models.',
    price: 39,
    currency: 'GHS',
    image: '/images/products/26300-35505-hyundai-kia-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '26300-35505',
    inStock: true,
  },
  {
    id: '30',
    slug: 'land-cruiser-v8-air-filter-17801-51020',
    name: 'Land Cruiser V8 Air Filter (17801-51020)',
    description: 'Air filter for Toyota Land Cruiser V8. Part No. 17801-51020. Designed for high-displacement V8 engine demands.',
    price: 104,
    currency: 'GHS',
    image: '/images/products/17801-51020-toyota-landcruiser-v8-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-51020',
    inStock: true,
  },
  {
    id: '31',
    slug: 'lc-prado-28l-air-filter-17801-11130',
    name: 'LC Prado 2.8L Air Filter (17801-11130)',
    description: 'Air filter for Toyota Land Cruiser Prado 2.8L. Part No. 17801-11130. Heavy-duty engine air protection.',
    price: 72,
    currency: 'GHS',
    image: '/images/products/17801-11130-toyota-lc-prado-2-8l-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-11130',
    inStock: true,
  },
  {
    id: '32',
    slug: 'mitsubishi-l200-oil-filter-md069782',
    name: 'Mitsubishi L200 Oil Filter (MD069782)',
    description: 'Oil filter for Mitsubishi L200 pickup. Part No. MD069782. Ensures engine durability on the L200.',
    price: 78,
    currency: 'GHS',
    image: '/images/products/md069782-mitsubishi-l200-oil-filte.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'MD069782',
    inStock: true,
  },
  {
    id: '33',
    slug: 'organic-zomi-palm-oil',
    name: 'Organic Zomi Palm Oil',
    description: 'Reliable Organic Zomi Palm Oil built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/organic-zomi-palm-oil.webp',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-023',
    inStock: true,
  },
  {
    id: '34',
    slug: 'prado-27l-air-filter-17801-30040',
    name: 'Prado 2.7L Air Filter (17801-30040)',
    description: 'Air filter for Toyota Prado 2.7L. Part No. 17801-30040. Ensures clean airflow for the Prado engine.',
    price: 72,
    currency: 'GHS',
    image: '/images/products/17801-30040-toyota-prado-2-7l-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-30040',
    inStock: true,
  },
  {
    id: '35',
    slug: 'rice-oil-combo',
    name: 'Rice & Oil Combo',
    description: 'Reliable Rice & Oil Combo built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/rice-and-oil-combo.webp',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-030',
    inStock: true,
  },
  {
    id: '36',
    slug: 'sally-sunflower-oil',
    name: 'Sally Sunflower Oil',
    description: 'Reliable Sally Sunflower Oil built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/sally-sunflower-oil.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-031',
    inStock: true,
  },
  {
    id: '37',
    slug: 'spanice-premium-brake-pads-curved-style-3',
    name: 'SPANICE Premium Brake Pads Curved Style 3',
    description: 'Reliable SPANICE Premium Brake Pads Curved Style 3 built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/spanice-premium-brake-pads-curved-style-3.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-037',
    inStock: true,
  },
  {
    id: '38',
    slug: 'spanice-premium-brake-pads-curved-style-3-pair',
    name: 'SPANICE Premium Brake Pads Curved Style 3 Pair',
    description: 'Reliable SPANICE Premium Brake Pads Curved Style 3 Pair built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/spanice-premium-brake-pads-curved-style-3-pair.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-036',
    inStock: true,
  },
  {
    id: '39',
    slug: 'spanice-premium-brake-pads-curved-style-3b',
    name: 'SPANICE Premium Brake Pads Curved Style 3b',
    description: 'Reliable SPANICE Premium Brake Pads Curved Style 3b built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/spanice-premium-brake-pads-curved-style-3b.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-038',
    inStock: true,
  },
  {
    id: '40',
    slug: 'spanice-premium-brake-pads-curved-style-3c',
    name: 'SPANICE Premium Brake Pads Curved Style 3c',
    description: 'Reliable SPANICE Premium Brake Pads Curved Style 3c built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/spanice-premium-brake-pads-curved-style-3c.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-039',
    inStock: true,
  },
  {
    id: '41',
    slug: 'spanice-premium-brake-pads-curved-style-3d',
    name: 'SPANICE Premium Brake Pads Curved Style 3d',
    description: 'Reliable SPANICE Premium Brake Pads Curved Style 3d built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/spanice-premium-brake-pads-curved-style-3d.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-040',
    inStock: true,
  },
  {
    id: '42',
    slug: 'spanice-premium-brake-pads-wide-style-1',
    name: 'SPANICE Premium Brake Pads Wide Style 1',
    description: 'Reliable SPANICE Premium Brake Pads Wide Style 1 built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/spanice-premium-brake-pads-wide-style-1.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-041',
    inStock: true,
  },
  {
    id: '43',
    slug: 'spanice-premium-brake-pads-wide-style-1b',
    name: 'SPANICE Premium Brake Pads Wide Style 1b',
    description: 'Reliable SPANICE Premium Brake Pads Wide Style 1b built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/spanice-premium-brake-pads-wide-style-1b.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-042',
    inStock: true,
  },
  {
    id: '44',
    slug: 'toyota-hilux-air-filter-17801-0l040',
    name: 'Toyota Hilux Air Filter (17801-0L040)',
    description: 'Air filter for Toyota Hilux. Part No. 17801-0L040. Robust filtration for Hilux diesel engines.',
    price: 78,
    currency: 'GHS',
    image: '/images/products/17801-0l040-toyota-hilux-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-0L040',
    inStock: true,
  },
  {
    id: '45',
    slug: 'toyota-inline-canister-fuel-filter',
    name: 'Toyota Inline Canister Fuel Filter',
    description: 'Reliable Toyota Inline Canister Fuel Filter built for consistent fit and performance, suitable for retail and distribution channels.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/toyota-inline-canister-fuel-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'NEW-043',
    inStock: true,
  },
  {
    id: '46',
    slug: 'toyota-land-cruiser-300-fuel-filter-23390-52060',
    name: 'Toyota Land Cruiser 300 Fuel Filter (23390-52060)',
    description: 'Fuel filter for Toyota Land Cruiser 300 Series. Part No. 23390-52060. Premium fuel protection for the LC300.',
    price: 130,
    currency: 'GHS',
    image: '/images/products/23390-52060-toyota-landcruiser-300-fuel-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-52060',
    inStock: true,
  },
  {
    id: '47',
    slug: 'toyota-lc-v8-fuel-filter-23390-51070',
    name: 'Toyota LC V8 Fuel Filter (23390-51070)',
    description: 'Fuel filter for Toyota Land Cruiser V8. Part No. 23390-51070. High-capacity fuel filtration for V8 engines.',
    price: 78,
    currency: 'GHS',
    image: '/images/products/23390-51070-toyota-lc-v8-fuel-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '23390-51070',
    inStock: true,
  },
  {
    id: '48',
    slug: 'toyota-rav4-avalon-air-filter-17801-77050',
    name: 'Toyota RAV4 / Avalon Air Filter (17801-77050)',
    description: 'Air filter for Toyota RAV4 and Avalon. Part No. 17801-77050. Premium airflow filtration for Toyota engines.',
    price: 59,
    currency: 'GHS',
    image: '/images/products/17801-77050-toyota-rav4-avalon-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-77050',
    inStock: true,
  },
  {
    id: '49',
    slug: 'toyota-rav4-highlander-air-filter-17801-25020',
    name: 'Toyota RAV4 / Highlander Air Filter (17801-25020)',
    description: 'Air filter for Toyota RAV4 and Highlander. Part No. 17801-25020. OEM-compatible fit for multiple Toyota SUVs.',
    price: 62,
    currency: 'GHS',
    image: '/images/products/17801-25020-toyota-rav4-highlander-air-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '17801-25020',
    inStock: true,
  },
  {
    id: '50',
    slug: 'toyota-rav4-front-brake-pad-d2076',
    name: 'Toyota RAV4 Front Brake Pad (D2076)',
    description: 'Front brake pads for Toyota RAV4. Part No. D2076. Precise fit and reliable stopping for the RAV4.',
    price: 260,
    currency: 'GHS',
    image: '/images/products/d2076-04465-az114-toyota-rav4-front-brake-pad.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D2076',
    inStock: true,
  },
  {
    id: '51',
    slug: 'toyota-rav4-rear-brake-pad-d1879',
    name: 'Toyota RAV4 Rear Brake Pad (D1879)',
    description: 'Rear brake pads for Toyota RAV4. Part No. D1879. Quiet and effective rear braking for the RAV4.',
    price: 195,
    currency: 'GHS',
    image: '/images/products/d1879-04466-02370-toyota-rav4-rear-brake-pad.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: 'D1879',
    inStock: true,
  },
  {
    id: '52',
    slug: 'toyota-vehicles-oil-filter-90915-yzzd4',
    name: 'Toyota Vehicles Oil Filter (90915-YZZD4)',
    description: 'Oil filter for Toyota vehicles. Part No. 90915-YZZD4. Compatible with multiple Toyota models.',
    price: 49,
    currency: 'GHS',
    image: '/images/products/90915-yzzd4-toyota-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '90915-YZZD4',
    inStock: true,
  },
  {
    id: '53',
    slug: 'toyota-vehicles-oil-filter-90915-yzze2',
    name: 'Toyota Vehicles Oil Filter (90915-YZZE2)',
    description: 'Oil filter for Toyota vehicles. Part No. 90915-YZZE2. Prevents contaminants from entering the engine.',
    price: 29,
    currency: 'GHS',
    image: '/images/products/90915-yzze2-toyota-vehicles-oil-filter.jpg',
    category: PRODUCT_CATEGORIES.AUTOPARTS,
    sku: '90915-YZZE2',
    inStock: true,
  },
  {
    id: '54',
    slug: 'egg-opener',
    name: 'Egg Opener',
    description: 'Quality Egg Opener suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/egg-opener.png',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-013',
    inStock: true,
  },
  {
    id: '55',
    slug: 'egg-opener-2',
    name: 'Egg Opener 2',
    description: 'Quality Egg Opener 2 suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/egg-opener-2.png',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'EGG-OPENER-2',
    inStock: true,
  },
  {
    id: '56',
    slug: 'egg-storage',
    name: 'Egg Storage',
    description: 'Quality Egg Storage suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/egg-storage.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-014',
    inStock: true,
  },
  {
    id: '57',
    slug: 'egg-storage-container',
    name: 'Egg Storage Container',
    description: 'Quality Egg Storage Container suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/egg-storage-container.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-012',
    inStock: true,
  },
  {
    id: '58',
    slug: 'egg-storage-container-50-pieces',
    name: 'Egg Storage Container 50 Pieces',
    description: 'Quality Egg Storage Container 50 Pieces suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/egg-storage-container-50-pieces.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-011',
    inStock: true,
  },
  {
    id: '59',
    slug: 'hoffmans-blender',
    name: 'Hoffmans Blender',
    description: 'Quality Hoffmans Blender suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/hoffmans-blender.png',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-020',
    inStock: true,
  },
  {
    id: '60',
    slug: 'portable-mini-fan-with-flashlight',
    name: 'Portable Mini Fan With Flashlight',
    description: 'Quality Portable Mini Fan With Flashlight suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/portable-mini-fan-with-flashlight.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-024',
    inStock: true,
  },
  {
    id: '61',
    slug: 'portable-mini-fan-with-phone-stand',
    name: 'Portable Mini Fan With Phone Stand',
    description: 'Quality Portable Mini Fan With Phone Stand suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/portable-mini-fan-with-phone-stand.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-025',
    inStock: true,
  },
  {
    id: '62',
    slug: 'rechargeable-fan-with-phone-stand',
    name: 'Rechargeable Fan With Phone Stand',
    description: 'Quality Rechargeable Fan With Phone Stand suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/rechargeable-fan-with-phone-stand.png',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-026',
    inStock: true,
  },
  {
    id: '63',
    slug: 'silver-crest-rice-cooker-fridge-guard-combo',
    name: 'Silver Crest Rice Cooker & Fridge Guard Combo',
    description: 'Quality Silver Crest Rice Cooker & Fridge Guard Combo suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/silver-crest-rice-cooker-and-fridge-guard-combo.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-033',
    inStock: true,
  },
  {
    id: '64',
    slug: 'silver-crest-rice-cooker-5l',
    name: 'Silver Crest Rice Cooker 5L',
    description: 'Quality Silver Crest Rice Cooker 5L suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/silver-crest-rice-cooker-5l.png',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'SILVER-CREST-RICE-COOKER-5L',
    inStock: true,
  },
  {
    id: '65',
    slug: 'sliver-crest-blender',
    name: 'Sliver Crest Blender',
    description: 'Quality Sliver Crest Blender suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/sliver-crest-blender.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-034',
    inStock: true,
  },
  {
    id: '66',
    slug: 'sliver-crest-rice-cooker',
    name: 'Sliver Crest Rice Cooker',
    description: 'Quality Sliver Crest Rice Cooker suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/sliver-crest-rice-cooker.webp',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-035',
    inStock: true,
  },
  {
    id: '67',
    slug: 'tv-guard',
    name: 'Tv Guard',
    description: 'Quality Tv Guard suitable for everyday use, with practical performance for homes, offices, and retail sales.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/tv-guard.png',
    category: PRODUCT_CATEGORIES.ELECTRONICS,
    sku: 'NEW-044',
    inStock: true,
  },
  {
    id: '68',
    slug: '30-days-beauty-secret-suppliments',
    name: '30 Days Beauty Secret Suppliments',
    description: '30 Days Beauty Secret Suppliments prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/30-days-beauty-secret-suppliments.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: '30-DAYS-BEAUTY-SECRET-SUPPLIMENTS',
    inStock: true,
  },
  {
    id: '69',
    slug: 'beef-stew-1-box-150-pieces-ghs-110000',
    name: 'Beef Stew 1 Box 150 Pieces GHS 1100.00',
    description: 'Beef Stew 1 Box 150 Pieces GHS 1100.00 prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/beef-stew-1-box-150-pieces-ghs-1100-00.webp',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-006',
    inStock: true,
  },
  {
    id: '70',
    slug: 'diblong-ginseng-chocolate-for-men',
    name: 'Diblong Ginseng Chocolate For Men',
    description: 'Diblong Ginseng Chocolate For Men prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/diblong-ginseng-chocolate-for-men.webp',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-008',
    inStock: true,
  },
  {
    id: '71',
    slug: 'gemini-generated-image-2jsxzc2jsxzc2jsx',
    name: 'Gemini Generated Image 2jsxzc2jsxzc2jsx',
    description: 'Gemini Generated Image 2jsxzc2jsxzc2jsx prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/gemini-generated-image-2jsxzc2jsxzc2jsx.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-015',
    inStock: true,
  },
  {
    id: '72',
    slug: 'life-springs-yoghurt-mixed-flavour-bundle',
    name: 'Life Springs Yoghurt Mixed Flavour Bundle',
    description: 'Life Springs Yoghurt Mixed Flavour Bundle prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/life-springs-yoghurt-mixed-flavour-bundle.jpeg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-021',
    inStock: true,
  },
  {
    id: '73',
    slug: 'luxor-color-washing-powder-10kg-color-safe-detergent',
    name: 'Luxor Color Washing Powder 10KG Color Safe Detergent',
    description: 'Luxor Color Washing Powder 10KG Color Safe Detergent prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/luxor-color-washing-powder-10kg-color-safe-detergent.webp',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-022',
    inStock: true,
  },
  {
    id: '74',
    slug: 'reed-diffuser',
    name: 'Reed Diffuser',
    description: 'Reed Diffuser prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/reed-diffuser.webp',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-027',
    inStock: true,
  },
  {
    id: '75',
    slug: 'reed-diffuser-oceanbreeze',
    name: 'Reed Diffuser Oceanbreeze',
    description: 'Reed Diffuser Oceanbreeze prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/reed-diffuser-oceanbreeze.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-028',
    inStock: true,
  },
  {
    id: '76',
    slug: 'reed-difuser',
    name: 'Reed Difuser',
    description: 'Reed Difuser prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/reed-difuser.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-029',
    inStock: true,
  },
  {
    id: '77',
    slug: 'shito',
    name: 'Shito',
    description: 'Shito prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/shito.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-032',
    inStock: true,
  },
  {
    id: '78',
    slug: 'snap-rice-5kg',
    name: 'Snap Rice 5kg',
    description: 'Snap Rice 5kg prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/snap-rice-5kg.png',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'SNAP-RICE-5KG',
    inStock: true,
  },
  {
    id: '79',
    slug: 'washing-powder',
    name: 'Washing Powder',
    description: 'Washing Powder prepared for wholesale and retail distribution with dependable quality and broad market demand.',
    price: 0,
    currency: 'GHS',
    image: '/images/products/washing-powder.jpg',
    category: PRODUCT_CATEGORIES.FMCG,
    sku: 'NEW-045',
    inStock: true,
  },
  {
    id: '80',
    slug: 'cotton-print-fabric',
    name: 'Cotton Print Fabric',
    description: 'High-quality printed cotton fabric for tailoring and fashion. Vibrant colors and patterns.',
    price: 55,
    currency: 'GHS',
    image: '/images/services/service3.jpg',
    category: PRODUCT_CATEGORIES.FABRICS,
    sku: 'FAB-001',
    inStock: true,
  },
  {
    id: '81',
    slug: 'ankara-wax-print',
    name: 'Ankara Wax Print',
    description: 'Authentic African wax print fabric. Perfect for traditional wear and fashion design.',
    price: 65,
    currency: 'GHS',
    image: '/images/services/service4.jpg',
    category: PRODUCT_CATEGORIES.FABRICS,
    sku: 'FAB-002',
    inStock: true,
  },
  {
    id: '82',
    slug: 'npk-fertilizer-50kg',
    name: 'NPK Fertilizer 50kg',
    description: 'Balanced NPK fertilizer for crop enhancement. Suitable for various agricultural applications.',
    price: 220,
    currency: 'GHS',
    image: '/images/services/service5.jpg',
    category: PRODUCT_CATEGORIES.AGRIC_INPUTS,
    sku: 'AGRI-001',
    inStock: true,
  },
  {
    id: '83',
    slug: 'herbicide-concentrate',
    name: 'Herbicide Concentrate',
    description: 'Effective herbicide for weed control in farms. Safe for crops when used as directed.',
    price: 150,
    currency: 'GHS',
    image: '/images/services/service6.jpg',
    category: PRODUCT_CATEGORIES.AGRIC_INPUTS,
    sku: 'AGRI-002',
    inStock: true,
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getAllProducts(): Product[] {
  return PRODUCTS;
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}
